name: Azure Static Web Apps CI/CD (CLI Deploy)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      # Install Azure CLI
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Log in with publish profile (store in repo secrets)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_STATICWEBAPP_CREDENTIALS }}

      # Deploy using Azure CLI (fast, no polling)
      - name: Deploy to Azure Static Web App
        run: |
          az staticwebapp upload \
            --name ai-geo-ui \
            --resource-group aitest \
            --source . \
            --app-location . \
            --output-location .next
