name: Azure Static Web Apps CI/CD (SWA CLI)

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (static export to ./out)
        run: npm run build

      - name: Install SWA CLI
        run: npm i -g @azure/static-web-apps-cli

      - name: Deploy via SWA CLI
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATICWEBAPP_API_TOKEN }}
        run: |
          # deploy the exported folder to Production
          swa deploy ./out --env production
